name: pizza_repository
description: The repo that handles pizza
publish_to: 'none'
version:  0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
#  equatable: ^2.0.5
#  firebase_auth: ^4.16.0
#  cloud_firestore: ^4.9.2
#  firebase_storage: ^11.6.0
#  rxdart: ^0.27.7
#  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true